### PR TITLE
Added support of the real class attributes validation.

### PR DESCRIPTION
**Pull request by resurtm**
Use case shown inside unit tests.

But as always feel free to contact with me via Skype to discuss it more. :-)

### CODE REVIEW

**Comment by resurtm** [comment]
Opinions and arguments on this? I think idea itself is correct, since `CActiveRecord` validation machinery allows to validate non-database/real class attributes. Implementing it in this extension would bring more consistency with `CActiveRecord`'s `save()` and `validate()` methods.

**Comment by creocoder** [comment]
Yes. Good idea. Can you change extension version in your PR?

**Comment by resurtm** [comment]
@creocoder, yes i'll do that today or tomorrow.

**Comment by resurtm** [comment]
Ok. I added additional assertions to the unit tests and rephrased code comments. It's ready to be merged now.

**Comment by creocoder** [comment]
Thanks for working on this.

**Pull request merged**
